language: php

php:
  - 5.6
  - 7.0

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - npm install -g gulp
  - npm install

script:
  - gulp sass
  - gulp version
  - vendor/bin/phpunit